services:

  mongodb-red-social:
    image: mongo:latest
    container_name: mongoc-red-social
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      # Estos son tus datos de acceso iniciales
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_PASSWORD
    volumes:
      # Esto sirve para que no pierdas tus datos al apagar el contenedor
      - mongo_red_social:/data/db

  mongodb-express-red-social:
    image: mongo-express:latest
    container_name: mongoc-express-red-social
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_DB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_DB_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongodb-red-social

      # no admin
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_DB_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_DB_PASSWORD
    depends_on:
      - mongodb-red-social

volumes:
  mongo_red_social:
